# Generated by Django 4.2.1 on 2023-05-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='post',
            new_name='department',
        ),
    ]
